export const adminConstants = {
    SHOW_VERIFICATION_REQUEST_TAB : "SHOW_VERIFICATION_REQUEST_TAB",
    SHOW_CONTENT_REPORTS_TAB : "SHOW_CONTENT_REPORTS_TAB",
    SHOW_AGENT_REQUEST_TAB : "SHOW_AGENT_REQUEST_TAB",
};