export const adminConstants = {
    SHOW_VERIFICATION_REQUEST_TAB : "SHOW_VERIFICATION_REQUEST_TAB",
    SHOW_CONTENT_REPORTS_TAB : "SHOW_CONTENT_REPORTS_TAB",
    SHOW_AGENT_REQUEST_TAB : "SHOW_AGENT_REQUEST_TAB",

    GET_PENDING_VERIFICATION_REQUEST_REQUEST: "GET_PENDING_VERIFICATION_REQUEST_REQUEST",
    GET_PENDING_VERIFICATION_REQUEST_SUCCESS: "GET_PENDING_VERIFICATION_REQUEST_SUCCESS",
    GET_PENDING_VERIFICATION_REQUEST_FAILURE: "GET_PENDING_VERIFICATION_REQUEST_FAILURE",

    GET_REPORT_REQUEST: "GET_REPORT_REQUEST",
    GET_REPORT_REQUEST_SUCCESS: "GET_REPORT_REQUEST_SUCCESS",
    GET_REPORT_REQUEST_FAILURE: "GET_REPORT_REQUEST_FAILURE",

    APPROVE_VERIFICATION_REQUEST_REQUEST :"APPROVE_VERIFICATION_REQUEST_REQUEST",
    APPROVE_VERIFICATION_REQUEST_SUCCESS :"APPROVE_VERIFICATION_REQUEST_SUCCESS",
    APPROVE_VERIFICATION_REQUEST_FAILURE :"APPROVE_VERIFICATION_REQUEST_FAILURE",

    REJECT_VERIFICATION_REQUEST_REQUEST :"REJECT_VERIFICATION_REQUEST_REQUEST",
    REJECT_VERIFICATION_REQUEST_SUCCESS :"REJECT_VERIFICATION_REQUEST_SUCCESS",
    REJECT_VERIFICATION_REQUEST_FAILURE :"REJECT_VERIFICATION_REQUEST_FAILURE",

    GET_PENDING_AGENT_REGISTRATION_REQUEST_REQUEST:"GET_PENDING_AGENT_REGISTRATION_REQUEST_REQUEST",
    GET_PENDING_AGENT_REGISTRATION_REQUEST_SUCCESS:"GET_PENDING_AGENT_REGISTRATION_REQUEST_SUCCESS",
    GET_PENDING_AGENT_REGISTRATION_REQUEST_FAILURE:"GET_PENDING_AGENT_REGISTRATION_REQUEST_FAILURE",

    APPROVE_AGENT_REGISTRATION_REQUEST_REQUEST :"APPROVE_AGENT_REGISTRATION_REQUEST_REQUEST",
    APPROVE_AGENT_REGISTRATION_REQUEST_SUCCESS :"APPROVE_AGENT_REGISTRATION_REQUEST_SUCCESS",
    APPROVE_AGENT_REGISTRATION_REQUEST_FAILURE :"APPROVE_AGENT_REGISTRATION_REQUEST_FAILURE",

    REJECT_AGENT_REGISTRATION_REQUEST_REQUEST :"REJECT_AGENT_REGISTRATION_REQUEST_REQUEST",
    REJECT_AGENT_REGISTRATION_REQUEST_SUCCESS :"REJECT_AGENT_REGISTRATION_REQUEST_SUCCESS",
    REJECT_AGENT_REGISTRATION_REQUEST_FAILURE :"REJECT_AGENT_REGISTRATION_REQUEST_FAILURE",
};