export const adsConstants = {
	SET_POST_CAMPAIGN_STATISTIC_REQUEST: "SET_POST_CAMPAIGN_STATISTIC_REQUEST",
	SET_POST_CAMPAIGN_STATISTIC_SUCCESS: "SET_POST_CAMPAIGN_STATISTIC_SUCCESS",
	SET_POST_CAMPAIGN_STATISTIC_FAILURE: "SET_POST_CAMPAIGN_STATISTIC_FAILURE",

	SET_STORY_CAMPAIGN_STATISTIC_REQUEST: "SET_STORY_CAMPAIGN_STATISTIC_REQUEST",
	SET_STORY_CAMPAIGN_STATISTIC_SUCCESS: "SET_STORY_CAMPAIGN_STATISTIC_SUCCESS",
	SET_STORY_CAMPAIGN_STATISTIC_FAILURE: "SET_STORY_CAMPAIGN_STATISTIC_FAILURE",
};
