export const messageConstants = {
	SET_USERS_CONVERSATIONS_REQUEST: "SET_USERS_CONVERSATIONS_REQUEST",
	SET_USERS_CONVERSATIONS_SUCCESS: "SET_USERS_CONVERSATIONS_SUCCESS",
	SET_USERS_CONVERSATIONS_FAILURE: "SET_USERS_CONVERSATIONS_FAILURE",

	SET_USER_MESSAGES_REQUEST: "SET_USER_MESSAGES_REQUEST",
	SET_USER_MESSAGES_SUCCESS: "SET_USER_MESSAGES_SUCCESS",
	SET_USER_MESSAGES_FAILURE: "SET_USER_MESSAGES_FAILURE",

	SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
	SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
	SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",

	VIEW_MESSAGES_REQUEST: "VIEW_MESSAGES_REQUEST",
	VIEW_MESSAGES_SUCCESS: "VIEW_MESSAGES_SUCCESS",
	VIEW_MESSAGES_FAILURE: "VIEW_MESSAGES_FAILURE",
};
