export const modalConstants = {
	OPEN_CREATE_STORY_MODAL: "OPEN_CREATE_STORY_MODAL",

	OPEN_ADD_TO_COLLECTION_MODAL: "OPEN_ADD_TO_COLLECTION_MODAL",
	CLOSE_ADD_TO_COLLECTION_MODAL: "CLOSE_ADD_TO_COLLECTION_MODAL",
};
