export const modalConstants = {
	OPEN_CREATE_STORY_MODAL: "OPEN_CREATE_STORY_MODAL",

	HIDE_POST_LIKED_BY_DETAILS: "HIDE_POST_LIKED_BY_DETAILS",
	SHOW_POST_LIKED_BY_DETAILS: "SHOW_POST_LIKED_BY_DETAILS",

	HIDE_POST_DISLIKES_MODAL: "HIDE_POST_DISLIKES_MODAL",
	SHOW_POST_DISLIKES_MODAL: "SHOW_POST_DISLIKES_MODAL",
};
