export const modalConstants = {
	OPEN_CREATE_STORY_MODAL: "OPEN_CREATE_STORY_MODAL",

	OPEN_ADD_TO_COLLECTION_MODAL: "OPEN_ADD_TO_COLLECTION_MODAL",
	CLOSE_ADD_TO_COLLECTION_MODAL: "CLOSE_ADD_TO_COLLECTION_MODAL",

	HIDE_POST_LIKED_BY_DETAILS: "HIDE_POST_LIKED_BY_DETAILS",
	SHOW_POST_LIKED_BY_DETAILS: "SHOW_POST_LIKED_BY_DETAILS",

	HIDE_POST_DISLIKES_MODAL: "HIDE_POST_DISLIKES_MODAL",
	SHOW_POST_DISLIKES_MODAL: "SHOW_POST_DISLIKES_MODAL",

	HIDE_VIEW_POST_MODAL: "HIDE_VIEW_POST_MODAL",
	SHOW_VIEW_POST_MODAL: "SHOW_VIEW_POST_MODAL",

	HIDE_STORY_SLIDER_MODAL: "HIDE_STORY_SLIDER_MODAL",
	SHOW_STORY_SLIDER_MODAL: "SHOW_STORY_SLIDER_MODAL",

	HIDE_STORY_SLIDER_HIGHLIGHTS_MODAL: "HIDE_STORY_SLIDER_HIGHLIGHTS_MODAL",
	SHOW_STORY_SLIDER_HIGHLIGHTS_MODAL: "SHOW_STORY_SLIDER_HIGHLIGHTS_MODAL",

	HIDE_POST_OPTIONS_MODAL: "HIDE_POST_OPTIONS_MODAL",
	SHOW_POST_OPTIONS_MODAL: "SHOW_POST_OPTIONS_MODAL",

	HIDE_POST_EDIT_MODAL: "HIDE_POST_EDIT_MODAL",
	SHOW_POST_EDIT_MODAL: "SHOW_POST_EDIT_MODAL",

	HIDE_STORY_SELECT_HIGHLIGHTS_MODAL: "HIDE_STORY_SELECT_HIGHLIGHTS_MODAL",
	SHOW_STORY_SELECT_HIGHLIGHTS_MODAL: "SHOW_STORY_SELECT_HIGHLIGHTS_MODAL",

	HIDE_FOLLOWING_MODAL: "HIDE_FOLLOWING_MODAL",

	HIDE_VIEW_POST_FOR_GUEST_MODAL: "HIDE_VIEW_POST_FOR_GUEST_MODAL",

	HIDE_NOTIFICATION_SETTINGS_MODAL: "HIDE_NOTIFICATION_SETTINGS_MODAL",
};
