export const notificationConstants = {
	SET_USER_NOTIFICATIONS_REQUEST: "SET_USER_NOTIFICATIONS_REQUEST",
	SET_USER_NOTIFICATIONS_SUCCESS: "SET_USER_NOTIFICATIONS_SUCCESS",
	SET_USER_NOTIFICATIONS_FAILURE: "SET_USER_NOTIFICATIONS_FAILURE",

	VIEW_NOTIFICATIONS_REQUEST: "VIEW_NOTIFICATIONS_REQUEST",
	VIEW_NOTIFICATIONS_SUCCESS: "VIEW_NOTIFICATIONS_SUCCESS",
	VIEW_NOTIFICATIONS_FAILURE: "VIEW_NOTIFICATIONS_FAILURE",

	NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
	MESSAGE_NOTIFICATION_RECEIVED: "MESSAGE_NOTIFICATION_RECEIVED",

	SET_PROFILE_NOTIFICATIONS_REQUEST: "SET_PROFILE_NOTIFICATIONS_REQUEST",
	SET_PROFILE_NOTIFICATIONS_SUCCESS: "SET_PROFILE_NOTIFICATIONS_SUCCESS",
	SET_PROFILE_NOTIFICATIONS_FAILURE: "SET_PROFILE_NOTIFICATIONS_FAILURE",

	EDIT_PROFILE_NOTIFICATIONS_REQUEST: "EDIT_PROFILE_NOTIFICATIONS_REQUEST",
	EDIT_PROFILE_NOTIFICATIONS_SUCCESS: "EDIT_PROFILE_NOTIFICATIONS_SUCCESS",
	EDIT_PROFILE_NOTIFICATIONS_FAILURE: "EDIT_PROFILE_NOTIFICATIONS_FAILURE",

	HIDE_NOTIFICATION_SETTINGS_SUCCESS_MESSAGE: "HIDE_NOTIFICATION_SETTINGS_SUCCESS_MESSAGE",
};
