export const notificationConstants = {
	SET_USER_NOTIFICATIONS_REQUEST: "SET_USER_NOTIFICATIONS_REQUEST",
	SET_USER_NOTIFICATIONS_SUCCESS: "SET_USER_NOTIFICATIONS_SUCCESS",
	SET_USER_NOTIFICATIONS_FAILURE: "SET_USER_NOTIFICATIONS_FAILURE",

	VIEW_NOTIFICATIONS_REQUEST: "VIEW_NOTIFICATIONS_REQUEST",
	VIEW_NOTIFICATIONS_SUCCESS: "VIEW_NOTIFICATIONS_SUCCESS",
	VIEW_NOTIFICATIONS_FAILURE: "VIEW_NOTIFICATIONS_FAILURE",

	NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
};
