export const postConstants = {
	TIMELINE_POSTS_REQUEST: "TIMELINE_POSTS_REQUEST",
	TIMELINE_POSTS_SUCCESS: "TIMELINE_POSTS_SUCCESS",
	TIMELINE_POSTS_FAILURE: "TIMELINE_POSTS_FAILURE",

	CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
	CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
	CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

	CREATE_POST_CAMPAIGN_REQUEST: "CREATE_POST_CAMPAIGN_REQUEST",
	CREATE_POST_CAMPAIGN_SUCCESS: "CREATE_POST_CAMPAIGN_SUCCESS",
	CREATE_POST_CAMPAIGN_FAILURE: "CREATE_POST_CAMPAIGN_FAILURE",

	EDIT_POST_REQUEST: "EDIT_POST_REQUEST",
	EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
	EDIT_POST_FAILURE: "EDIT_POST_FAILURE",

	LIKE_POST_REQUEST: "LIKE_POST_REQUEST",
	LIKE_POST_SUCCESS: "LIKE_POST_SUCCESS",
	LIKE_POST_FAILURE: "LIKE_POST_FAILURE",

	UNLIKE_POST_REQUEST: "UNLIKE_POST_REQUEST",
	UNLIKE_POST_SUCCESS: "UNLIKE_POST_SUCCESS",
	UNLIKE_POST_FAILURE: "UNLIKE_POST_FAILURE",

	DISLIKE_POST_REQUEST: "DISLIKE_POST_REQUEST",
	DISLIKE_POST_SUCCESS: "DISLIKE_POST_SUCCESS",
	DISLIKE_POST_FAILURE: "DISLIKE_POST_FAILURE",

	UNDISLIKE_POST_REQUEST: "UNDISLIKE_POST_REQUEST",
	UNDISLIKE_POST_SUCCESS: "UNDISLIKE_POST_SUCCESS",
	UNDISLIKE_POST_FAILURE: "UNDISLIKE_POST_FAILURE",

	SET_USER_COLLECTIONS_REQUEST: "SET_USER_COLLECTIONS_REQUEST",
	SET_USER_COLLECTIONS_SUCCESS: "SET_USER_COLLECTIONS_SUCCESS",
	SET_USER_COLLECTIONS_FAILURE: "SET_USER_COLLECTIONS_FAILURE",

	SET_USER_PROFILE_COLLECTIONS_REQUEST: "SET_USER_PROFILE_COLLECTIONS_REQUEST",
	SET_USER_PROFILE_COLLECTIONS_SUCCESS: "SET_USER_PROFILE_COLLECTIONS_SUCCESS",
	SET_USER_PROFILE_COLLECTIONS_FAILURE: "SET_USER_PROFILE_COLLECTIONS_FAILURE",

	SET_USER_PROFILE_COLLECTIONS_POSTS_REQUEST: "SET_USER_PROFILE_COLLECTIONS_POSTS_REQUEST",
	SET_USER_PROFILE_COLLECTIONS_POSTS_SUCCESS: "SET_USER_PROFILE_COLLECTIONS_POSTS_SUCCESS",
	SET_USER_PROFILE_COLLECTIONS_POSTS_FAILURE: "SET_USER_PROFILE_COLLECTIONS_POSTS_FAILURE",

	PROFILE_POST_DETAILS_REQUEST: "PROFILE_POST_DETAILS_REQUEST",
	PROFILE_POST_DETAILS_SUCCESS: "PROFILE_POST_DETAILS_SUCCESS",
	PROFILE_POST_DETAILS_FAILURE: "PROFILE_POST_DETAILS_FAILURE",

	SET_CAMPAIGN_POST_DETAILS_REQUEST: "SET_CAMPAIGN_POST_DETAILS_REQUEST",
	SET_CAMPAIGN_POST_DETAILS_SUCCESS: "SET_CAMPAIGN_POST_DETAILS_SUCCESS",
	SET_CAMPAIGN_POST_DETAILS_FAILURE: "SET_CAMPAIGN_POST_DETAILS_FAILURE",

	ADD_POST_TO_COLLECTION_REQUEST: "ADD_POST_TO_COLLECTION_REQUEST",
	ADD_POST_TO_COLLECTION_SUCCESS: "ADD_POST_TO_COLLECTION_SUCCESS",
	ADD_POST_TO_COLLECTION_FAILURE: "ADD_POST_TO_COLLECTION_FAILURE",

	DELETE_POST_FROM_COLLECTION_REQUEST: "DELETE_POST_FROM_COLLECTION_REQUEST",
	DELETE_POST_FROM_COLLECTION_SUCCESS: "DELETE_POST_FROM_COLLECTION_SUCCESS",
	DELETE_POST_FROM_COLLECTION_FAILURE: "DELETE_POST_FROM_COLLECTION_FAILURE",

	CREATE_COLLECTION_REQUEST: "CREATE_COLLECTION_REQUEST",
	CREATE_COLLECTION_SUCCESS: "CREATE_COLLECTION_SUCCESS",
	CREATE_COLLECTION_FAILURE: "CREATE_COLLECTION_FAILURE",

	COMMENT_POST_REQUEST: "COMMENT_POST_REQUEST",
	COMMENT_POST_SUCCESS: "COMMENT_POST_SUCCESS",
	COMMENT_POST_FAILURE: "COMMENT_POST_FAILURE",

	SET_USER_POSTS_REQUEST: "SET_USER_POSTS_REQUEST",
	SET_USER_POSTS_SUCCESS: "SET_USER_POSTS_SUCCESS",
	SET_USER_POSTS_FAILURE: "SET_USER_POSTS_FAILURE",
	SET_USER_POSTS_UNAUTHORIZED_FAILURE: "SET_USER_POSTS_UNAUTHORIZED_FAILURE",

	GUEST_TIMELINE_POSTS_SUCCESS: "GUEST_TIMELINE_POSTS_SUCCESS",
	GUEST_TIMELINE_POSTS_REQUEST: "GUEST_TIMELINE_POSTS_REQUEST",
	GUEST_TIMELINE_POSTS_FAILURE: "GUEST_TIMELINE_POSTS_FAILURE",

	PROFILE_POST_DETAILS_FOR_GUEST_REQUEST: "PROFILE_POST_DETAILS_FOR_GUEST_REQUEST",
	PROFILE_POST_DETAILS_FOR_GUEST_SUCCESS: "PROFILE_POST_DETAILS_FOR_GUEST_SUCCESS",
	PROFILE_POST_DETAILS_FOR_GUEST_FAILURE: "PROFILE_POST_DETAILS_FOR_GUEST_FAILURE",

	LIKED_POSTS_REQUEST: "LIKED_POSTS_REQUEST",
	LIKED_POSTS_SUCCESS: "LIKED_POSTS_SUCCESS",
	LIKED_POSTS_FAILURE: "LIKED_POSTS_FAILURE",

	DISLIKED_POSTS_REQUEST: "DISLIKED_POSTS_REQUEST",
	DISLIKED_POSTS_SUCCESS: "DISLIKED_POSTS_SUCCESS",
	DISLIKED_POSTS_FAILURE: "DISLIKED_POSTS_FAILURE",

	REPORT_POST_REQUEST: "REPORT_POST_REQUEST",
	REPORT_POST_SUCCESS: "REPORT_POST_SUCCESS",
	REPORT_POST_FAILURE: "REPORT_POST_FAILURE",

	SET_POST_FOR_PAGE_REQUEST: "SET_POST_FOR_PAGE_REQUEST",
	SET_POST_FOR_PAGE_SUCCESS: "SET_POST_FOR_PAGE_SUCCESS",
	SET_POST_FOR_PAGE_FAILURE: "SET_POST_FOR_PAGE_FAILURE",

	SET_USER_CAMPAIGN_POSTS_REQUEST: "SET_USER_CAMPAIGN_POSTS_REQUEST",
	SET_USER_CAMPAIGN_POSTS_SUCCESS: "SET_USER_CAMPAIGN_POSTS_SUCCESS",
	SET_USER_CAMPAIGN_POSTS_FAILURE: "SET_USER_CAMPAIGN_POSTS_FAILURE",

	HIDE_POST_CAMPAIGN_OPTION_ALERTS: "HIDE_POST_CAMPAIGN_OPTION_ALERTS",

	SET_POST_CAMPAIGN_REQUEST: "SET_POST_CAMPAIGN_REQUEST",
	SET_POST_CAMPAIGN_SUCCESS: "SET_POST_CAMPAIGN_SUCCESS",
	SET_POST_CAMPAIGN_FAILURE: "SET_POST_CAMPAIGN_FAILURE",

	UPDATE_POST_CAMPAIGN_REQUEST: "UPDATE_POST_CAMPAIGN_REQUEST",
	UPDATE_POST_CAMPAIGN_SUCCESS: "UPDATE_POST_CAMPAIGN_SUCCESS",
	UPDATE_POST_CAMPAIGN_FAILURE: "UPDATE_POST_CAMPAIGN_FAILURE",

	DELETE_POST_CAMPAIGN_REQUEST: "DELETE_POST_CAMPAIGN_REQUEST",
	DELETE_POST_CAMPAIGN_SUCCESS: "DELETE_POST_CAMPAIGN_SUCCESS",
	DELETE_POST_CAMPAIGN_FAILURE: "DELETE_POST_CAMPAIGN_FAILURE",
};
