export const postConstants = {
	TIMELINE_POSTS_REQUEST: "TIMELINE_POSTS_REQUEST",
	TIMELINE_POSTS_SUCCESS: "TIMELINE_POSTS_SUCCESS",
	TIMELINE_POSTS_FAILURE: "TIMELINE_POSTS_FAILURE",
	
	CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
	CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
	CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

	LIKE_POST_REQUEST: "LIKE_POST_REQUEST",
	LIKE_POST_SUCCESS: "LIKE_POST_SUCCESS",
	LIKE_POST_FAILURE: "LIKE_POST_FAILURE",

	UNLIKE_POST_REQUEST: "UNLIKE_POST_REQUEST",
	UNLIKE_POST_SUCCESS: "UNLIKE_POST_SUCCESS",
	UNLIKE_POST_FAILURE: "UNLIKE_POST_FAILURE",
};
