export const profileSettingsConstants = {
	SHOW_EDIT_PROFILE_PAGE: "SHOW_EDIT_PROFILE_PAGE",
	SHOW_VERIFY_ACCOUNT_PAGE: "SHOW_VERIFY_ACCOUNT_PAGE",
	SHOW_EDIT_NOTIFICATIONS_PAGE: "SHOW_EDIT_NOTIFICATIONS_PAGE",
	SHOW_EDIT_PRIVACY_SETTINGS_PAGE: "SHOW_EDIT_PRIVACY_SETTINGS_PAGE",

	CREATE_VERIFICATION_REQUEST_REQUEST: "CREATE_VERIFICATION_REQUEST_REQUEST",
	CREATE_VERIFICATION_REQUEST_SUCCESS: "CREATE_VERIFICATION_REQUEST_SUCCESS",
	CREATE_VERIFICATION_REQUEST_FAILURE: "CREATE_VERIFICATION_REQUEST_FAILURE",

	CHECK_IF_USER_HAS_PENDING_REQUEST_REQUEST: "CHECK_IF_USER_HAS_PENDING_REQUEST_REQUEST",
	CHECK_IF_USER_HAS_PENDING_REQUEST_SUCCESS: "CHECK_IF_USER_HAS_PENDING_REQUEST_SUCCESS",
	CHECK_IF_USER_HAS_PENDING_REQUEST_FAILURE: "CHECK_IF_USER_HAS_PENDING_REQUEST_FAILURE",
};
