export const profileSettingsConstants = {
	SHOW_EDIT_PROFILE_PAGE: "SHOW_EDIT_PROFILE_PAGE",
	SHOW_VERIFY_ACCOUNT_PAGE: "SHOW_VERIFY_ACCOUNT_PAGE",
	SHOW_EDIT_NOTIFICATIONS_PAGE: "SHOW_EDIT_NOTIFICATIONS_PAGE",

	CREATE_VERIFICATION_REQUEST_REQUEST: "CREATE_VERIFICATION_REQUEST_REQUEST",
	CREATE_VERIFICATION_REQUEST_SUCCESS: "CREATE_VERIFICATION_REQUEST_SUCCESS",
	CREATE_VERIFICATION_REQUEST_FAILURE: "CREATE_VERIFICATION_REQUEST_FAILURE",
};
