export const storyConstants = {
	CREATE_STORY_REQUEST: "CREATE_STORY_REQUEST",
	CREATE_STORY_SUCCESS: "CREATE_STORY_SUCCESS",
	CREATE_STORY_FAILURE: "CREATE_STORY_FAILURE",

	STORYLINE_STORY_REQUEST: "STORYLINE_STORY_REQUEST",
	STORYLINE_STORY_SUCCESS: "STORYLINE_STORY_SUCCESS",
	STORYLINE_STORY_FAILURE: "STORYLINE_STORY_FAILURE",

	USER_HIGHLIGHTS_STORY_REQUEST: "USER_HIGHLIGHTS_STORY_REQUEST",
	USER_HIGHLIGHTS_STORY_SUCCESS: "USER_HIGHLIGHTS_STORY_SUCCESS",
	USER_HIGHLIGHTS_STORY_FAILURE: "USER_HIGHLIGHTS_STORY_FAILURE",

	SHOW_HIGHLIGHTS_NAME_INPUT: "SHOW_HIGHLIGHTS_NAME_INPUT",
	HIDE_HIGHLIGHTS_NAME_INPUT: "HIDE_HIGHLIGHTS_NAME_INPUT",

	SHOW_HIGHLIGHTS_MODAL_ERROR_MESSAGE: "SHOW_HIGHLIGHTS_MODAL_ERROR_MESSAGE",
	HIDE_HIGHLIGHTS_MODAL_ERROR_MESSAGE: "HIDE_HIGHLIGHTS_MODAL_ERROR_MESSAGE",

	CREATE_HIGHLIGHTS_STORY_REQUEST: "CREATE_HIGHLIGHTS_STORY_REQUEST",
	CREATE_HIGHLIGHTS_STORY_SUCCESS: "CREATE_HIGHLIGHTS_STORY_SUCCESS",
	CREATE_HIGHLIGHTS_STORY_FAILURE: "CREATE_HIGHLIGHTS_STORY_FAILURE",

	PROFILE_HIGHLIGHTS_REQUEST: "CREATE_HIGHLIGHTS_STORY_REQUEST",
	PROFILE_HIGHLIGHTS_SUCCESS: "PROFILE_HIGHLIGHTS_SUCCESS",
	PROFILE_HIGHLIGHTS_FAILURE: "PROFILE_HIGHLIGHTS_FAILURE",

	FIND_HIGHLIGHT_BY_NAME_REQUEST: "FIND_HIGHLIGHT_BY_NAME_REQUEST",
	FIND_HIGHLIGHT_BY_NAME_SUCCESS: "FIND_HIGHLIGHT_BY_NAME_SUCCESS",
	FIND_HIGHLIGHT_BY_NAME_FAILURE: "FIND_HIGHLIGHT_BY_NAME_FAILURE",
};
