export const storyConstants = {
	CREATE_STORY_REQUEST: "CREATE_STORY_REQUEST",
	CREATE_STORY_SUCCESS: "CREATE_STORY_SUCCESS",
	CREATE_STORY_FAILURE: "CREATE_STORY_FAILURE",

	STORYLINE_STORY_REQUEST: "STORYLINE_STORY_REQUEST",
	STORYLINE_STORY_SUCCESS: "STORYLINE_STORY_SUCCESS",
	STORYLINE_STORY_FAILURE: "STORYLINE_STORY_FAILURE",

	USER_HIGHLIGHTS_STORY_REQUEST: "USER_HIGHLIGHTS_STORY_REQUEST",
	USER_HIGHLIGHTS_STORY_SUCCESS: "USER_HIGHLIGHTS_STORY_SUCCESS",
	USER_HIGHLIGHTS_STORY_FAILURE: "USER_HIGHLIGHTS_STORY_FAILURE",
};
