export const userConstants = {
	REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
	REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
	REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
	REGISTER_VALIDATION_FAILURE: "REGISTER_VALIDATION_FAILURE",

	UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
	UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
	UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	LOGIN_TWO_REQUEST: "LOGIN_TWO_REQUEST",
	LOGIN_TWO_SUCCESS: "LOGIN_TWO_SUCCESS",
	LOGIN_TWO_FAILURE: "LOGIN_TWO_FAILURE",

	RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
	RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
	RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

	RESET_PASSWORD_LINK_REQUEST: "RESET_PASSWORD_LINK_REQUEST",
	RESET_PASSWORD_LINK_SUCCESS: "RESET_PASSWORD_LINK_SUCCESS",
	RESET_PASSWORD_LINK_FAILURE: "RESET_PASSWORD_LINK_FAILURE",

	RESEND_ACTIVATION_LINK_REQUEST: "RESEND_ACTIVATION_LINK_REQUEST",
	RESEND_ACTIVATION_LINK_SUCCESS: "RESEND_ACTIVATION_LINK_SUCCESS",
	RESEND_ACTIVATION_LINK_FAILURE: "RESEND_ACTIVATION_LINK_FAILURE",

	BLOCKED_USER_EMAIL_REQUEST: "BLOCKED_USER_EMAIL_REQUEST",

	GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
	GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
	GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

	SET_USER_FOLLOWING_REQUEST: "SET_USER_FOLLOWING_REQUEST",
	SET_USER_FOLLOWING_SUCCESS: "SET_USER_FOLLOWING_SUCCESS",
	SET_USER_FOLLOWING_FAILURE: "SET_USER_FOLLOWING_FAILURE",

	FOLLOW_USER_REQUEST: "FOLLOW_USER_REQUEST",
	FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
	FOLLOW_USER_SEND_REQUEST_SUCCESS: "FOLLOW_USER_SEND_REQUEST_SUCCESS",
	FOLLOW_USER_FAILURE: "FOLLOW_USER_FAILURE",

	UNFOLLOW_USER_REQUEST: "UNFOLLOW_USER_REQUEST",
	UNFOLLOW_USER_SUCCESS: "UNFOLLOW_USER_SUCCESS",
	UNFOLLOW_USER_FAILURE: "UNFOLLOW_USER_FAILURE",

	FOLLOW_REQUESTS_REQUEST: "FOLLOW_REQUESTS_REQUEST",
	FOLLOW_REQUESTS_SUCCESS: "FOLLOW_REQUESTS_SUCCESS",
	FOLLOW_REQUESTS_FAILURE: "FOLLOW_REQUESTS_FAILURE",

	ACCEPT_FOLLOW_REQUESTS_REQUEST: "ACCEPT_FOLLOW_REQUESTS_REQUEST",
	ACCEPT_FOLLOW_REQUESTS_SUCCESS: "ACCEPT_FOLLOW_REQUESTS_SUCCESS",
	ACCEPT_FOLLOW_REQUESTS_FAILURE: "ACCEPT_FOLLOW_REQUESTS_FAILURE",

	REGISTRATION_SHOW_QR_CODE: "REGISTRATION_SHOW_QR_CODE",

	LOGIN_DATA_REQUEST: "LOGIN_DATA_REQUEST",
	LOGIN_DATA_SUCCESS: "LOGIN_DATA_SUCCESS",
	LOGIN_DATA_FAILURE: "LOGIN_DATA_FAILURE",

	MUTE_USER_SUCCESS: "MUTE_USER_SUCCESS",
	UNMUTE_USER_SUCCESS: "UNMUTE_USER_SUCCESS",

	BLOCK_USER_SUCCESS: "BLOCK_USER_SUCCESS",
	UNBLOCK_USER_SUCCESS: "UNBLOCK_USER_SUCCESS",

	BLOCK_USER_REQUEST: "BLOCK_USER_REQUEST",
	UNBLOCK_USER_REQUEST: "UNBLOCK_USER_REQUEST",

	CHECK_IF_USER_VERIFIED_REQUEST: "CHECK_IF_USER_VERIFIED_REQUEST",
	CHECK_IF_USER_VERIFIED_SUCCESS: "CHECK_IF_USER_VERIFIED_SUCCESS",
	CHECK_IF_USER_VERIFIED_FAILURE: "CHECK_IF_USER_VERIFIED_FAILURE",

	GET_FOLLOW_RECOMMENDATION_REQUEST: "GET_FOLLOW_RECOMMENDATION_REQUEST",
	GET_FOLLOW_RECOMMENDATION_SUCCESS: "GET_FOLLOW_RECOMMENDATION_SUCCESS",
	GET_FOLLOW_RECOMMENDATION_FAILURE: "GET_FOLLOW_RECOMMENDATION_FAILURE",

	RECOMMENDED_FOLLOW_USER_REQUEST: "RECOMMENDED_FOLLOW_USER_REQUEST",
	RECOMMENDED_FOLLOW_USER_SUCCESS: "RECOMMENDED_FOLLOW_USER_SUCCESS",
	RECOMMENDED_FOLLOW_USER_SEND_REQUEST_SUCCESS: "RECOMMENDED_FOLLOW_USER_SEND_REQUEST_SUCCESS",
	RECOMMENDED_FOLLOW_USER_FAILURE: "RECOMMENDED_FOLLOW_USER_FAILURE",

	SHOW_AGENT_REGISTRATION_TAB: "SHOW_AGENT_REGISTRATION_TAB",
	SHOW_USER_REGISTRATION_TAB: "SHOW_USER_REGISTRATION_TAB",

	REGISTER_AGENT_SUCCESS: "REGISTER_AGENT_SUCCESS",
};
