export const userConstants = {
	REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
	REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
	REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
	REGISTER_VALIDATION_FAILURE: "REGISTER_VALIDATION_FAILURE",

	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
	RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
	RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

	RESET_PASSWORD_LINK_REQUEST: "RESET_PASSWORD_LINK_REQUEST",
	RESET_PASSWORD_LINK_SUCCESS: "RESET_PASSWORD_LINK_SUCCESS",
	RESET_PASSWORD_LINK_FAILURE: "RESET_PASSWORD_LINK_FAILURE",

	RESEND_ACTIVATION_LINK_REQUEST: "RESEND_ACTIVATION_LINK_REQUEST",
	RESEND_ACTIVATION_LINK_SUCCESS: "RESEND_ACTIVATION_LINK_SUCCESS",
	RESEND_ACTIVATION_LINK_FAILURE: "RESEND_ACTIVATION_LINK_FAILURE",

	BLOCKED_USER_EMAIL_REQUEST: "BLOCKED_USER_EMAIL_REQUEST",

	GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
	GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
	GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

	SET_USER_FOLLOWING_REQUEST: "SET_USER_FOLLOWING_REQUEST",
	SET_USER_FOLLOWING_SUCCESS: "SET_USER_FOLLOWING_SUCCESS",
	SET_USER_FOLLOWING_FAILURE: "SET_USER_FOLLOWING_FAILURE",

	FOLLOW_USER_REQUEST: "FOLLOW_USER_REQUEST",
	FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
	FOLLOW_USER_FAILURE: "FOLLOW_USER_FAILURE",

	UNFOLLOW_USER_REQUEST: "UNFOLLOW_USER_REQUEST",
	UNFOLLOW_USER_SUCCESS: "UNFOLLOW_USER_SUCCESS",
	UNFOLLOW_USER_FAILURE: "UNFOLLOW_USER_FAILURE",
};
