export const modalConstants = {
	HIDE_CREATE_PRODUCT_MODAL: "HIDE_CREATE_PRODUCT_MODAL",
	SHOW_CREATE_PRODUCT_MODAL: "SHOW_CREATE_PRODUCT_MODAL",

	HIDE_EDIT_PRODUCT_MODAL: "HIDE_EDIT_PRODUCT_MODAL",
	SHOW_EDIT_PRODUCT_MODAL: "SHOW_EDIT_PRODUCT_MODAL",
};
