export const orderConstants = {
	ADD_PRODUCT_TO_ORDER: "ADD_PRODUCT_TO_ORDER",
	REMOVE_PRODUCT_FROM_ORDER: "REMOVE_PRODUCT_FROM_ORDER",
	SET_PRODUCT_COUNT_TO_ORDER: "SET_PRODUCT_COUNT_TO_ORDER",

	CHECKOUT_MODAL_HIDE_MESSAGE: "CHECKOUT_MODAL_HIDE_MESSAGE",

	CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
	CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
	CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",
};
