export const productConstants = {
	SET_PRODUCTS_REQUEST: "SET_PRODUCTS_REQUEST",
	SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
	SET_PRODUCTS_FAILURE: "SEt_PRODUCTS_FAILURE",

	CREATE_PRODUCT_MODAL_HIDE_ERROR: "CREATE_PRODUCT_MODAL_HIDE_ERROR",
	CREATE_PRODUCT_IMAGE_DESELECTED: "CREATE_PRODUCT_IMAGE_DESELECTED",
	CREATE_PRODUCT_IMAGE_SELECTED: "CREATE_PRODUCT_IMAGE_SELECTED",

	CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
	CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
	CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",

	FIND_BY_ID_PRODUCT_REQUEST: "FIND_BY_ID_PRODUCT_REQUEST",
	FIND_BY_ID_PRODUCT_SUCCESS: "FIND_BY_ID_PRODUCT_SUCCESS",
	FIND_BY_ID_PRODUCT_FAILURE: "FIND_BY_ID_PRODUCT_FAILURE",

	EDIT_PRODUCT_IMAGE_DESELECTED: "EDIT_PRODUCT_IMAGE_DESELECTED",
	EDIT_PRODUCT_IMAGE_SELECTED: "EDIT_PRODUCT_IMAGE_SELECTED",
	EDIT_PRODUCT_MODAL_HIDE_ERROR: "EDIT_PRODUCT_MODAL_HIDE_ERROR",

	EDIT_PRODUCT_REQUEST: "EDIT_PRODUCT_REQUEST",
	EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
	EDIT_PRODUCT_FAILURE: "EDIT_PRODUCT_FAILURE",

	EDIT_PRODUCT_IMAGE_REQUEST: "EDIT_PRODUCT_IMAGE_REQUEST",
	EDIT_PRODUCT_IMAGE_SUCCESS: "EDIT_PRODUCT_IMAGE_SUCCESS",
	EDIT_PRODUCT_IMAGE_FAILURE: "EDIT_PRODUCT_IMAGE_FAILURE",

	DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
	DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
	DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

	CREATE_CAMPAIGN_REQUEST: "CREATE_CAMPAIGN_REQUEST",
	CREATE_CAMPAIGN_SUCCESS: "CREATE_CAMPAIGN_SUCCESS",
	CREATE_CAMPAIGN_FAILURE: "CREATE_CAMPAIGN_FAILURE",

	SET_CAMPAIGNS_STATS_REQUEST: "SET_CAMPAIGNS_STATS_REQUEST",
	SET_CAMPAIGNS_STATS_SUCCESS: "SET_CAMPAIGNS_STATS_SUCCESS",
	SET_CAMPAIGNS_STATS_FAILURE: "SET_CAMPAIGNS_STATS_FAILURE",
};
